
### login admin
POST http://localhost:6868/login
Content-Type: application/json

{
  "email": "bvujicic@gmail.com",
  "password": "26N64AcWYszk"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
  %}


### login user
POST http://localhost:6868/login
Content-Type: application/json

{
  "email": "petar.petrovic@eprotokol.com",
  "password": "test"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
  %}


### list all users
GET  http://localhost:6868/api/user
Accept: application/json
Authorization: Bearer {{accessToken}}

### create user
POST  http://localhost:6868/api/user
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": "nemanja.123@axiomqz.com",
  "name": "nemanja z",
  "unitName": "a",
  "positionName": "a"
}

### cancel invitation
POST  http://localhost:6868/api/user/10013/cancelInvitation
Accept: application/json
Authorization: Bearer {{accessToken}}

### list all tags
GET  http://localhost:6868/api/project/tag/details?sort=id&order=DESC
Accept: application/json
Authorization: Bearer {{accessToken}}


### list all projects
GET  http://localhost:6868/api/project
Accept: application/json
Authorization: Bearer {{accessToken}}


### list all tag details
GET  http://localhost:6868/api/project/tag/details
Accept: application/json
Authorization: Bearer {{accessToken}}


### add tag
POST http://localhost:6868/api/project/tag
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "color": "#b7b1dd",
  "name": "test"
}


### delete tag
DELETE http://localhost:6868/api/project/tag/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### list all projects
GET  http://localhost:6868/api/project?tagIds=[4,5]
Accept: application/json
Authorization: Bearer {{accessToken}}


### list active projects
GET  http://localhost:6868/api/project
Accept: application/json
Authorization: Bearer {{accessToken}}


### get one project
GET  http://localhost:6868/api/project/3
Accept: application/json
Authorization: Bearer {{accessToken}}


### add project to favorites
PUT http://localhost:6868/api/project/10037/favorite/add
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### remove project from favorites
PUT http://localhost:6868/api/project/10037/favorite/remove
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}




### archive project
PUT  http://localhost:6868/api/project/1/archive
Accept: application/json
Authorization: Bearer {{accessToken}}


### archive project
PUT  http://localhost:6868/api/project/1/unarchive
Accept: application/json
Authorization: Bearer {{accessToken}}



### create project
POST http://localhost:6868/api/project/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "proj",
  "description": "desc xxx 0001",
  "archived": false,
  "memberIds": [1],
  "organizerIds": [1],
  "documents": [],
  "remainders": [],
  "tagIds": [1, 2],
  "date": "2022-01-14"
}



### update project
PUT http://localhost:6868/api/project/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "proj",
  "description": "desc xxx 0002",
  "archived": false,
  "memberIds": [ 1],
  "organizerIds": [1],
  "documents": [],
  "remainders": [],
  "tagIds": [1,2],
  "date": "2022-01-14"
}


### update project
PUT http://localhost:6868/api/project/49
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "id": 49,
  "title": "proj",
  "description": "desc xxx 0001",
  "archived": false,
  "memberIds": [24, 1],
  "organizerIds": [1],
  "documents": [],
  "remainders": [],
  "tagIds": [4, 5],
  "date": "2022-01-14"
}


### update project
PUT http://localhost:6868/api/project/49
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Test 123",
  "description": "test",
  "organizerIds": [
    1
  ],
  "memberIds": [
    24
  ],
  "tagIds": [
    4
  ],
  "date": "2022-01-14"
}

###  project documents
GET  http://localhost:6868/api/project/44/document
Accept: application/json
Authorization: Bearer {{accessToken}}

###  project comments
GET  http://localhost:6868/api/project/3/comment
Accept: application/json
Authorization: Bearer {{accessToken}}


###  get project tasks
GET  http://localhost:6868/api/project/3/task
Accept: application/json
Authorization: Bearer {{accessToken}}



###  get ONE project task
GET  http://localhost:6868/api/project/3/task/2
Accept: application/json
Authorization: Bearer {{accessToken}}



###  create project task
POST  http://localhost:6868/api/project/3/task
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "authorId": 1,
  "userId": 1,
  "title": "task title 3",
  "text": "text of the task 3",
  "status": "NEW",
  "time": "2022-06-30 12:00:00"
}



###  update project task
PUT  http://localhost:6868/api/project/3/task/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "authorId": 1,
  "userId": 1,
  "title": "task title 2 updated",
  "text": "text of the task updated",
  "status": "NEW",
  "time": "2022-06-30 12:00:00"
}


###  update project task status
PUT  http://localhost:6868/api/project/3/task/2/status/IN_PROGRESS
Accept: application/json
Authorization: Bearer {{accessToken}}

