
### login admin
POST http://localhost:6868/login
Content-Type: application/json

{
  "email": "bvujicic@gmail.com",
  "password": "26N64AcWYszk"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
  %}


### projects
GET http://localhost:6868/api/project?page=0&size=15
Accept: application/json
Authorization: Bearer {{accessToken}}



### list all tags
GET  http://localhost:6868/api/project/tag/details?sort=id&order=DESC
Accept: application/json
Authorization: Bearer {{accessToken}}
